# Generated by Django 4.2.16 on 2024-11-12 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=6)),
                ('fin_co_no', models.CharField(max_length=7)),
                ('fin_prdt_cd', models.CharField(max_length=20)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=200)),
                ('join_way', models.CharField(max_length=255)),
                ('mtrt_int', models.TextField()),
                ('spcl_cnd', models.TextField()),
                ('join_deny', models.CharField(max_length=1)),
                ('join_member', models.CharField(max_length=100)),
                ('etc_note', models.TextField()),
                ('max_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dcls_strt_day', models.DateField()),
                ('dcls_end_day', models.DateField(blank=True, null=True)),
                ('fin_co_subm_day', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=6)),
                ('fin_co_no', models.CharField(max_length=7)),
                ('fin_prdt_cd', models.CharField(max_length=20)),
                ('intr_rate_type', models.CharField(max_length=1)),
                ('intr_rate_type_nm', models.CharField(max_length=10)),
                ('rsrv_type', models.CharField(max_length=1)),
                ('rsrv_type_nm', models.CharField(max_length=20)),
                ('save_trm', models.CharField(max_length=2)),
                ('intr_rate', models.FloatField(blank=True, null=True)),
                ('intr_rate2', models.FloatField(blank=True, null=True)),
                ('installment_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='myapp.installmentproduct')),
            ],
        ),
    ]
