# Generated by Django 4.2.16 on 2024-11-22 02:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Open_API', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationproduct',
            name='like_users',
            field=models.ManyToManyField(related_name='like_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
