# Generated by Django 4.2.16 on 2024-11-23 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Open_API', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together=set(),
        ),
    ]
