# Generated by Django 4.2.16 on 2024-11-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Open_API', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
