# Generated by Django 4.2.16 on 2024-11-21 12:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Open_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationproduct',
            name='likes_bank',
            field=models.ManyToManyField(related_name='likes_bank', to=settings.AUTH_USER_MODEL),
        ),
    ]
