# Generated by Django 4.2.16 on 2024-11-21 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Open_API', '0002_integrationproduct_likes_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationproduct',
            name='likes_bank',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='Open_API.integrationproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'bank_product')},
            },
        ),
    ]
