# Generated by Django 4.2.16 on 2024-11-13 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(blank=True, max_length=6, null=True)),
                ('fin_co_no', models.CharField(blank=True, max_length=7, null=True)),
                ('fin_prdt_cd', models.CharField(blank=True, max_length=100, null=True)),
                ('crdt_prdt_type', models.CharField(blank=True, max_length=1, null=True)),
                ('kor_co_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('fin_prdt_nm', models.CharField(blank=True, max_length=200, null=True)),
                ('join_way', models.CharField(blank=True, max_length=255, null=True)),
                ('cb_name', models.CharField(blank=True, max_length=255, null=True)),
                ('crdt_prdt_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('dcls_strt_day', models.DateField(blank=True, null=True)),
                ('dcls_end_day', models.DateField(blank=True, null=True)),
                ('fin_co_subm_day', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crdt_lend_rate_type', models.CharField(blank=True, max_length=1, null=True)),
                ('crdt_lend_rate_type_nm', models.CharField(blank=True, max_length=50, null=True)),
                ('crdt_grad_1', models.FloatField(blank=True, null=True)),
                ('crdt_grad_4', models.FloatField(blank=True, null=True)),
                ('crdt_grad_5', models.FloatField(blank=True, null=True)),
                ('crdt_grad_6', models.FloatField(blank=True, null=True)),
                ('crdt_grad_10', models.FloatField(blank=True, null=True)),
                ('crdt_grad_11', models.FloatField(blank=True, null=True)),
                ('crdt_grad_12', models.FloatField(blank=True, null=True)),
                ('crdt_grad_13', models.FloatField(blank=True, null=True)),
                ('crdt_grad_avg', models.FloatField(blank=True, null=True)),
                ('loan_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='PersonalCreditLoan.loanproduct')),
            ],
        ),
    ]
