# Generated by Django 4.2.16 on 2024-11-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('cur_unit', models.TextField()),
                ('cur_nm', models.TextField()),
                ('ttb', models.TextField(blank=True, null=True)),
                ('tts', models.TextField(blank=True, null=True)),
                ('deal_bas_r', models.TextField()),
                ('bkpr', models.TextField()),
                ('yy_efee_r', models.TextField(default='0')),
                ('ten_dd_efee_r', models.TextField(default='0')),
                ('kftc_deal_bas_r', models.TextField()),
                ('kftc_bkpr', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
